// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar/protobuf/admin.proto

package com.scalar.admin.rpc;

public interface PauseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.PauseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool wait_outstanding = 1;</code>
   * @return The waitOutstanding.
   */
  boolean getWaitOutstanding();
}
