// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar/protobuf/admin.proto

package com.scalar.admin.rpc;

/**
 * Protobuf type {@code rpc.PauseRequest}
 */
public final class PauseRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpc.PauseRequest)
    PauseRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PauseRequest.newBuilder() to construct.
  private PauseRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PauseRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PauseRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scalar.admin.rpc.AdminProto.internal_static_rpc_PauseRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scalar.admin.rpc.AdminProto.internal_static_rpc_PauseRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scalar.admin.rpc.PauseRequest.class, com.scalar.admin.rpc.PauseRequest.Builder.class);
  }

  private int bitField0_;
  public static final int WAIT_OUTSTANDING_FIELD_NUMBER = 1;
  private boolean waitOutstanding_ = false;
  /**
   * <code>bool wait_outstanding = 1;</code>
   * @return The waitOutstanding.
   */
  @java.lang.Override
  public boolean getWaitOutstanding() {
    return waitOutstanding_;
  }

  public static final int MAX_PAUSE_WAIT_TIME_FIELD_NUMBER = 2;
  private long maxPauseWaitTime_ = 0L;
  /**
   * <code>optional int64 max_pause_wait_time = 2;</code>
   * @return Whether the maxPauseWaitTime field is set.
   */
  @java.lang.Override
  public boolean hasMaxPauseWaitTime() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int64 max_pause_wait_time = 2;</code>
   * @return The maxPauseWaitTime.
   */
  @java.lang.Override
  public long getMaxPauseWaitTime() {
    return maxPauseWaitTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (waitOutstanding_ != false) {
      output.writeBool(1, waitOutstanding_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(2, maxPauseWaitTime_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (waitOutstanding_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, waitOutstanding_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, maxPauseWaitTime_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scalar.admin.rpc.PauseRequest)) {
      return super.equals(obj);
    }
    com.scalar.admin.rpc.PauseRequest other = (com.scalar.admin.rpc.PauseRequest) obj;

    if (getWaitOutstanding()
        != other.getWaitOutstanding()) return false;
    if (hasMaxPauseWaitTime() != other.hasMaxPauseWaitTime()) return false;
    if (hasMaxPauseWaitTime()) {
      if (getMaxPauseWaitTime()
          != other.getMaxPauseWaitTime()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WAIT_OUTSTANDING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getWaitOutstanding());
    if (hasMaxPauseWaitTime()) {
      hash = (37 * hash) + MAX_PAUSE_WAIT_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMaxPauseWaitTime());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scalar.admin.rpc.PauseRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.admin.rpc.PauseRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.admin.rpc.PauseRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.admin.rpc.PauseRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.admin.rpc.PauseRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.admin.rpc.PauseRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.admin.rpc.PauseRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalar.admin.rpc.PauseRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scalar.admin.rpc.PauseRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.scalar.admin.rpc.PauseRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scalar.admin.rpc.PauseRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalar.admin.rpc.PauseRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scalar.admin.rpc.PauseRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rpc.PauseRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpc.PauseRequest)
      com.scalar.admin.rpc.PauseRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scalar.admin.rpc.AdminProto.internal_static_rpc_PauseRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scalar.admin.rpc.AdminProto.internal_static_rpc_PauseRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scalar.admin.rpc.PauseRequest.class, com.scalar.admin.rpc.PauseRequest.Builder.class);
    }

    // Construct using com.scalar.admin.rpc.PauseRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      waitOutstanding_ = false;
      maxPauseWaitTime_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scalar.admin.rpc.AdminProto.internal_static_rpc_PauseRequest_descriptor;
    }

    @java.lang.Override
    public com.scalar.admin.rpc.PauseRequest getDefaultInstanceForType() {
      return com.scalar.admin.rpc.PauseRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.scalar.admin.rpc.PauseRequest build() {
      com.scalar.admin.rpc.PauseRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scalar.admin.rpc.PauseRequest buildPartial() {
      com.scalar.admin.rpc.PauseRequest result = new com.scalar.admin.rpc.PauseRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.scalar.admin.rpc.PauseRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.waitOutstanding_ = waitOutstanding_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.maxPauseWaitTime_ = maxPauseWaitTime_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scalar.admin.rpc.PauseRequest) {
        return mergeFrom((com.scalar.admin.rpc.PauseRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scalar.admin.rpc.PauseRequest other) {
      if (other == com.scalar.admin.rpc.PauseRequest.getDefaultInstance()) return this;
      if (other.getWaitOutstanding() != false) {
        setWaitOutstanding(other.getWaitOutstanding());
      }
      if (other.hasMaxPauseWaitTime()) {
        setMaxPauseWaitTime(other.getMaxPauseWaitTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              waitOutstanding_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              maxPauseWaitTime_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean waitOutstanding_ ;
    /**
     * <code>bool wait_outstanding = 1;</code>
     * @return The waitOutstanding.
     */
    @java.lang.Override
    public boolean getWaitOutstanding() {
      return waitOutstanding_;
    }
    /**
     * <code>bool wait_outstanding = 1;</code>
     * @param value The waitOutstanding to set.
     * @return This builder for chaining.
     */
    public Builder setWaitOutstanding(boolean value) {
      
      waitOutstanding_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool wait_outstanding = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWaitOutstanding() {
      bitField0_ = (bitField0_ & ~0x00000001);
      waitOutstanding_ = false;
      onChanged();
      return this;
    }

    private long maxPauseWaitTime_ ;
    /**
     * <code>optional int64 max_pause_wait_time = 2;</code>
     * @return Whether the maxPauseWaitTime field is set.
     */
    @java.lang.Override
    public boolean hasMaxPauseWaitTime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int64 max_pause_wait_time = 2;</code>
     * @return The maxPauseWaitTime.
     */
    @java.lang.Override
    public long getMaxPauseWaitTime() {
      return maxPauseWaitTime_;
    }
    /**
     * <code>optional int64 max_pause_wait_time = 2;</code>
     * @param value The maxPauseWaitTime to set.
     * @return This builder for chaining.
     */
    public Builder setMaxPauseWaitTime(long value) {
      
      maxPauseWaitTime_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 max_pause_wait_time = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxPauseWaitTime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      maxPauseWaitTime_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc.PauseRequest)
  }

  // @@protoc_insertion_point(class_scope:rpc.PauseRequest)
  private static final com.scalar.admin.rpc.PauseRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scalar.admin.rpc.PauseRequest();
  }

  public static com.scalar.admin.rpc.PauseRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PauseRequest>
      PARSER = new com.google.protobuf.AbstractParser<PauseRequest>() {
    @java.lang.Override
    public PauseRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PauseRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PauseRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scalar.admin.rpc.PauseRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

