// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar/protobuf/admin.proto

package com.scalar.admin.rpc;

public interface PausedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.PausedResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool paused = 1;</code>
   * @return The paused.
   */
  boolean getPaused();
}
