// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar/protobuf/admin.proto

// Protobuf Java Version: 3.25.3
package com.scalar.admin.rpc;

public interface PauseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.PauseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool wait_outstanding = 1;</code>
   * @return The waitOutstanding.
   */
  boolean getWaitOutstanding();

  /**
   * <code>optional int64 max_pause_wait_time = 2;</code>
   * @return Whether the maxPauseWaitTime field is set.
   */
  boolean hasMaxPauseWaitTime();
  /**
   * <code>optional int64 max_pause_wait_time = 2;</code>
   * @return The maxPauseWaitTime.
   */
  long getMaxPauseWaitTime();
}
