// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar/protobuf/admin.proto

package com.scalar.admin.rpc;

public interface StatsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.StatsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * json-formatted
   * </pre>
   *
   * <code>string stats = 1;</code>
   * @return The stats.
   */
  java.lang.String getStats();
  /**
   * <pre>
   * json-formatted
   * </pre>
   *
   * <code>string stats = 1;</code>
   * @return The bytes for stats.
   */
  com.google.protobuf.ByteString
      getStatsBytes();
}
